<template>

  <div class="CVImg">
  <div class="home-TUIKit-main">
    <div :class="env?.isH5 ? 'conversation-h5' : 'conversation'" v-show="!env?.isH5 || currentModel === 'conversation'">
      <TUISearch class="search" />
      <TUIConversation style="background: linear-gradient(to bottom right, #fafafa, #d9f1f6);" @current="handleCurrentConversation" />
    </div>
    <div class="chat" v-show="!env?.isH5 || currentModel === 'message'">
      <TUIChat>
        <h2>Welcome to Tabibito Online Chat</h2>
<!--        <div class="CVImg"></div>-->
      </TUIChat>
    </div>
    <Drag :show="showCall" class="callkit-drag-container" domClassName="callkit-drag-container">

      <!-- TUICallKit 组件：通话 UI 组件主体 -->
      <TUICallKit
          :allowedMinimized="true"
          :allowedFullScreen="false"
          :beforeCalling="beforeCalling"
          :afterCalling="afterCalling"
          :onMinimized="onMinimized"
          :onMessageSentByMe="onMessageSentByMe"
      />
    </Drag>
    <Drag :show="showCallMini" class="callkit-drag-container-mini" domClassName="callkit-drag-container-mini">
      <!-- TUICallKitMini 组件：通话 UI 悬浮窗组件，提供最小化功能 -->
      <TUICallKitMini style="position: static" />
    </Drag>
      <button class="gpt-chat-btn" :class="{ active: showGptChatView }" @click="toggleGptChatView">
        <img src="../../assets/ChatGPT_logo.png" alt="GPT Chat Button" />
      </button>
      <gpt-chat-view v-show="showGptChatView" class="gpt-chat-view" />
    </div>
  </div>
</template>


<script lang="ts">
import { TUIComponents, TUICore, genTestUserSig } from '../../TUIKit';
import { TUICallKit } from '@tencentcloud/call-uikit-vue';

import {defineComponent, getCurrentInstance, reactive, ref, toRefs} from 'vue';
import { TUIEnv } from '../../TUIKit/TUIPlugin';
import Drag from '../../TUIKit/TUIComponents/components/drag';
import { handleErrorPrompts } from '../../TUIKit/TUIComponents/container/utils';
import NavigationBar from "../GeneralComponents/navigationBar.vue";
import {useStore} from "../../store.js";
import GptChatView from "./gptChatView.vue";


export default defineComponent({
  name: 'chatView',
  components: {
    GptChatView,
    NavigationBar,
    Drag,
  },
  beforeCreate() {
    let store = useStore();
    if (!store.user_login_status){
      this.$router.push('/login')
    } else {

      const SDKAppID = 1400807426; // Your SDKAppID
      const secretKey = 'c5b8e9dad518ccf326e1978d4aedb1c5d80fee9723c8a5710728577fbf501ff3'; //Your secretKey
      const userID = store.name.toString(); // User ID


      // init TUIKit
      const TUIKit = TUICore.init({
        SDKAppID,
      });
      // TUIKit add TUIComponents
      TUIKit.use(TUIComponents);
      // TUIKit add TUICallKit
      TUIKit.use(TUICallKit);


      // login TUIKit
      TUIKit.login({
        userID: userID,
        userSig: genTestUserSig({
          SDKAppID,
          secretKey,
          userID,
        }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
      });

      this.$myApp.config.globalProperties.$myApp.use(TUIKit);
      // 在路由进入时动态加载所需内容
      // import('path/to/some/module').then((module) => {
      //     // 执行所需操作
      // });
    }
  },
  mounted() {
    window.addEventListener('popstate', this.handleBackButton);
  },
  beforeDestroy() {
    window.removeEventListener('popstate', this.handleBackButton);
  },
  setup() {
    const data = reactive({
      env: TUIEnv(),
      currentModel: 'conversation',
      showCall: false,
      showCallMini: false,
    });
    const TUIServer = (window as any)?.TUIKitTUICore?.TUIServer;
    const handleCurrentConversation = (value: string) => {
      data.currentModel = value ? 'message' : 'conversation';
    };
    // beforeCalling：在拨打电话前与收到通话邀请前执行
    const beforeCalling = (type: string, error: any) => {
      if (error) {
        handleErrorPrompts(error, type);
        return;
      }
      data.showCall = true;
    };
    // afterCalling：结束通话后执行
    const afterCalling = () => {
      data.showCall = false
      ;
      data.showCallMini = false;
    };
    // onMinimized：组件切换最小化状态时执行
    const onMinimized = (oldMinimizedStatus: boolean, newMinimizedStatus: boolean) => {
      data.showCall = !newMinimizedStatus;
      data.showCallMini = newMinimizedStatus;
    };
    // onMessageSentByMe：在整个通话过程内发送消息时执行
    const onMessageSentByMe = async (message: any) => {
      TUIServer?.TUIChat?.handleMessageSentByMeToView(message);
      return;
    };
    return {
      ...toRefs(data),
      handleCurrentConversation,
      beforeCalling,
      afterCalling,
      onMinimized,
      onMessageSentByMe,
    };
  },
  methods: {
    toggleGptChatView() {
      this.showGptChatView = !this.showGptChatView;
    },
    handleBackButton() {
      this.$router.push('/load');
    }
  },
  data() {
    return {
      showGptChatView: false
    }
  }
});
</script>


<style scoped>
.gpt-chat-btn {
  display: flex;
  justify-content: center;
  align-items: center;
  position: fixed;
  bottom: 15px;
  right: 100px;
  z-index: 9999;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  background-color: rgb(223, 239, 247);
  transition: background-color 0.3s ease-in-out;
}

.gpt-chat-btn:hover {
  cursor: pointer;
}

.gpt-chat-btn.active {
  background-color: #fff;
}

.gpt-chat-btn img {
  width: 30px;
  height: 30px;
  opacity: 0.5;
  transition: opacity 0.3s ease-in-out;
}

.gpt-chat-btn.active img {
  opacity: 1;
}

.gpt-chat-btn:active {
  background-color: #ccc;
}

.gpt-chat-view {
  position: fixed;
  z-index: 9999;
  bottom: 100px;
  right: 20px;
}

.chatHead{
  position: relative;
}

.home-TUIKit-main {
  display: flex;
  height: 100vh;
  overflow: hidden;
}
.search {
  padding: 12px;
}
.conversation {
  min-width: 285px;
  flex: 0 0 24%;
  border-right: 1px solid #f4f5f9;
}
.conversation-h5 {
  flex: 1;
  border-right: 1px solid #f4f5f9;
}
.chat {
  flex: 1;
  height: 100%;
  position: relative;
}
.callkit-drag-container {
  left: calc(50% - 25rem);
  top: calc(50% - 18rem);
  width: 50rem;
  height: 36rem;
  border-radius: 16px;
  box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;
}
.callkit-drag-container-mini {
  width: 168px;
  height: 56px;
  right: 10px;
  top: 70px;
}

.CVImg{
  background: linear-gradient(to bottom right, #fafafa, #d1eff5);
}

</style>
